
version: '3.8'
services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=expenses
      - POSTGRES_USER=postgreuser
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/app
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
    depends_on:
      - db

  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile 
    volumes:
      - ./back_end:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
