# Generated by Django 5.0.6 on 2024-07-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.AddField(
            model_name='expense',
            name='month',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='expense',
            name='year',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
