# Generated by Django 5.0.6 on 2024-07-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_date_expense_month_expense_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
    ]
